name: Cleanup Notebook Metadata

on:
  push:
    branches: [main]
    paths:
      - '**.ipynb'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to clean (leave empty for current branch)'
        required: false
        default: ''

jobs:
  clean-notebooks:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Clean notebook metadata
        run: |
          # Find all .ipynb files and process them
          find . -name "*.ipynb" -type f | while read -r file; do
            echo "Processing: $file"
            # Create a temporary file
            temp_file=$(mktemp)
            # Remove metadata.widgets and save to temp file
            jq 'del(.metadata.widgets)' "$file" > "$temp_file"
            # Replace original file with cleaned version
            mv "$temp_file" "$file"
          done
      
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Clean notebook metadata: remove widgets"
          git push origin ${{ github.event.inputs.branch || github.ref_name }}
